---
apiVersion: v1
kind: Service
metadata:
  name: env-test-service
  # namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: env-test
  type: LoadBalancer
